# Site Settings
title: Profile of Qiao
url: 'csqiaoxu.github.io'
baseurl: 'csqiaoxu.github.io' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Qiao Xu
tagline: 本科在读
pic: photo.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '个人信条：努力，乐观，向上！不忘初心.<br> 
所获荣誉：
    全国大学生电子设计大赛省一等奖<br>
    全国大学生数学竞赛省三等奖<br>
'

#sidebar links
email: 201457506105@ytu.edu.cn
phone: 15963511252
website: blog.csdn.net/qq_27513221 #do not add http://
github: GerogeWilde
WeChat: 'qiaoxu1996628'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
